// jsframeworks/vue/src/components/UI/MySelect.vue
<template>
   <select v-model="modelValue" @change="changeOption">
      <option disabled value="">select something from the list</option>
      <option v-for="option in options" :key="option.value" value="option.value">{{option.name}}</option>
   </select>
</template>

<script>
export default {
   name: 'my-select',
   props:{
      modelValue:{
         type:String
      },
      options:{
         type: Array,
         default:() => []
      }
   },
   methods:{
      changeOption(event){
         this.emit('update:modelValue', event.target.value);
      }
   }
}
</script>

<style>

</style>

// jsframeworks/project/src/components/UI/select/MySelect.jsx
import React from "react";

const MySelect = ({options, defaultValue, value, onChange}) => {
   return (
      <select 
      style={{margin: '15px 0 0 15px'}} 
      value={value}
      onChange={event => onChange(event.target.value)}
      >
         <option disabled={true} value="">{defaultValue}</option>
         {options.map(option =>
            <option key={option.value} value={option.value}>{option.name}</option>
         )}
      </select>
   );
};


export default MySelect;
