// jsframeworks/project/src/components/PostItem.jsx
import React from "react";
import MyButton from "./UI/button/MyButton";
import DeleteButton from "./UI/button/DeleteButton";
import { useHistory } from "react-router-dom";

const PostItem = (props) => {
  const router = useHistory()

   return(
      <div className="post">
        <div className="post__content">
          <strong>{props.post.id} {props.post.title}</strong>
          <div>
            {props.post.body}
          </div>
        </div>
        <div className="post__btns">
          <MyButton onClick={() => router.push(`/posts/${props.post.id}`)}>кнопка открыть сообщения</MyButton>
          <MyButton onClick={() => props.remove(props.post)}>кнопка удаления сообщения</MyButton>
        </div>
      </div>
   )
}

export default PostItem;

// jsframeworks/vue/src/components/PostItem.vue
<template>
   <div class="post">
      <div>
         <div><strong>Title:</strong>{{post.title}}</div>
         <div><strong>Description:</strong>{{post.body}}</div>
         <div>likes = {{ $store.state.likes }}</div>
      </div>
      <div class="post__btns">
         <my-button
            @click="$emit('remove', post)"
         >
            Delete
         </my-button>
         <my-button
            @click="$router.push(`/posts/${post.title}`)"
         >
            Open
         </my-button>
      </div>
   </div>
</template>

<script>
export default{
   props:{
      post:{
         type: Object,
         require: true,
      }
   }
}
</script>

<style>
.post__btns{
   margin: 0 0 0 91%;
   display: grid;
}
</style>
